 <div style="background-color:#5257af;font-size: 40px; color:white"><center><p><strong>Terms and Conditions</strong></p><center></div>

<p>Welcome to the mobile phone application, “Motley” (“Application”) and website “motleymart.com" (“Website”). The contents of the Application and Website are the property of Dakkhan Digital Marketing Private Limited (the “Company”). The Company is in the business of providing platform for consumers to transact with third party sellers, who have been granted access on application or website. (the “Services”). The Company does not provide any services to user other than providing marketplace as a platform to transact at their own cost and risk through application or website.</p>

<p>It is strongly recommended that your use of the Application is governed by the following terms and conditions (“Terms of Use”). If you do not agree to these Terms of Use, you cannot use or the Application.</p>

<p>By using the Application, you signify your agreement to these Terms of Use as well as the Company’s privacy policy, which is hereby incorporated by reference herein. These Terms of Use set out the legally binding terms of the Services as well as the terms of use of the Application.</p>

<p>For the purpose of these Terms of Use, wherever the context so requires, “you” or “your” shall mean any natural or legal person who visits the Application and/or transacts business on the Application and/ or uses the Services by providing registration information. The terms “Motley” “motleymart.com”, “Application”, “we”, “us”, “our” shall mean the Company.

<p>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THE APPLICATION TO AVAIL THE SERVICES

<p>These Terms of Use along with the Company’s privacy policy extend to users who visit the Application but do not avail the Services or transact business on the Application as well as users who are registered and are authorized by the Application to transact business or avail the Services on the Application. The Company reserves the right to modify or terminate any portion of the Application or the Services offered by the Company for any reason, without notice and without liability to you or any third party. You are responsible for regularly reviewing these Terms of Use so that you will be apprised of any changes. Nothing in these Terms of Use should be construed to confer any rights to any third party beneficiaries.</p> 

<p>1. Your Account and Registration</p>

<p>1. You will be required to register on the Application or website and create an account prior to the completion of any transaction on the Application.
2. Use of the Application is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Application. You represent and warrant that you are at least 18 years old and all information you submit is true, accurate and complete while registering the account on Application. If you are a minor i.e. under the age of 18 years, you shall not register as a user of the Application and shall not transact on or use the Application. As a minor if you wish to use or transact on the Application, such use or transaction may be made by your legal guardian or parents. The Company reserves the right to terminate your membership and / or refuse to provide you with access to the Application if it is brought to the Company's notice or if it is discovered that you are under the age of 18 years. You must keep your account details up-to-date at all times including through provision of a valid and working email address. You will be responsible for all activities that occur under your account. You may not sell or otherwise transfer your Application account to another person or entity.
3. To register on the Application you will have to provide your Personal Information (being such information that identifies, relates to or describes you, or which is capable of being associated with you) including your mobile number and email address.
4. Registration is only a one time process and if you have previously registered, you shall login /sign in to your registered account using your phone number.
5. Registration on the Application is free for all users. However, a fee may be charged for subscribing to any new/additional Services offered by the Company exclusively to registered users. The Company reserves the right to change the fee policy applicable to such paid registration. Changes to the fee policy will be posted on the Application and such changes shall become effective immediately after they are posted on the Application.
6. Privacy statement: You understand that through your use of the Application or any software, services or application programming interfaces available on or through the Application, including in user forums or blogs on or accessed via the Application, you consent to the collection, storage, sharing and use by us or any of our affiliates, of Personal Information collected from you. You agree that any such Personal Information may be viewed by others. You understand and acknowledge that if you post personal information online that is accessible to the public, you may receive unsolicited messages from other parties in return and the Company will not be responsible for the use or misuse of such information by third parties. We expressly disclaim any legal liability, whether civil, criminal, pertaining to the content of, security of, or rights in, any part of such information. You have the right to control your Personal Information and except as set out in these Terms of Use or in the privacy policy of the Company, we will not disclose your Personal Information unless we have your permission or unless we are required to or permitted to do so under applicable laws.
2. Access
1. You are responsible for maintaining the confidentiality of your account and password and for restricting and preventing unauthorized access to your account. You agree to accept responsibility for all activities that occur under your account or password.
2. You can access and update account details on the Application. You shall ensure that the account details provided to the Application are correct and complete at all times. The Application reserves the right to refuse access to the Application, terminate accounts, remove or edit content at any time without notice to you.
3. The Company will endeavor to ensure that access to and availability of the Application remains uninterrupted and error free. However, access to the Application may occasionally be suspended or restricted to allow for repairs, maintenance, or for the introduction of new facilities and services.
4. Cookie Policy: A cookie is a small text file that we place on your mobile device to enable various features of the Application. "Cookies" are used to store user preferences and to track user trends, so as to enhance your interactive experience and generally improve our Services to you. You can change your cookie settings to accept or not accept cookies in your browser settings. If you do accept a "cookie", you thereby agree to our use of any personal information collected by us using that Cookie.

    <p>3. Limited Licence for Access</p>

<p>1. The Company grants you a limited licence to access and make personal use of the Application, but not to download (other than page caching) or to modify it (or any portion thereof), except with prior written consent of the Company and / or its affiliates, as may be applicable.
2. This licence does not include any resale or commercial use of the Application or its contents; any collection and use of any product listings, descriptions, or prices, any derivative use of the Application or its contents, any downloading or copying of account information for the benefit of another seller, or any use of data mining, robots, or similar data gathering and extraction tools.
3. The Application or any portion thereof (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without the prior written consent of the Company and / or its affiliates, as may be applicable.
4. You will not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of the Company and its affiliates without their prior written consent. You will not use any meta tags or any other "hidden text" utilizing the Company’s or its affiliates' names or trademarks without the prior written consent of the Company and / or its affiliates, as may be applicable. Any unauthorized use will terminate the permission or license granted by the Company and / or its affiliates, as may be applicable.
5.  You will not use any logo or other proprietary graphic or trademark of the Company/ Application as part of the link without prior written consent of the Company and / or its affiliates, as may be applicable.
6. You shall not use the Application in any way that causes, or may be likely to cause damage or impairment to the Application or in any manner harms the Company or any other person or entity (as determined by the Company in its sole discretion) or interrupt free access to it in any way. You are solely responsible for that you post on the Application. Please therefore choose carefully the information that you post on the Application. You shall not use the Application to host, display, upload, post, submit, distribute, modify, publish, transmit, update or share any information that:
1. belongs to another person and to which you do not have any right;
2. is grossly harmful, harassing, blasphemous defamatory obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
3. harms minors in any way;
4. infringes any patent, trademark, copyright or other proprietary rights;
5. infringes upon any third party’s right of privacy, personality or endorsement;
6. violates these Terms of Use or any applicable law for the time being in force including, but not limited to, those governing false advertising, consumer protection and safety, discrimination, terror and hate speech;
7. advertises or promotes anything including personal or commercial sites/applications.
8. deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
9. impersonates another person;
10. contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of the Application and/or the Services or any connected network or any computer resource, or otherwise interferes with any entity’s use or enjoyment of the Application and/or the Services; and
11. threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insults any other nation.
This is a non-exhaustive list which should be used as a guide on what you must not post on the Application or transmit to other users.<p>

<p>7. You will not engage in any form of antisocial, disrupting, or destructive acts, including "flaming," "spamming," "flooding," "trolling," "phishing" and "griefing" as those terms are commonly understood and used on the internet.
8. You will not delete or modify any content of the Application and/or Services including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that you do not own or have express permission to modify.
    4. Platform for Transaction and Communication</p>

<p>1. The Application is a platform that users utilise to meet and interact with our experts and suppliers or Sellers (as defined below) for their requirements. The Company is not and cannot be a party to or control in any manner any transaction between the Application's users and suppliers/Sellers.
2. All commercial/contractual terms are offered by and agreed to between you and the sellers of the products and services (“Seller/s”) alone. The commercial/contractual terms include without limitation, price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. The Company does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between you and the Sellers. Once you agree to purchase a product or avail a service from a Seller, you also agree to be bound by the terms and conditions of use, of the Seller. All transactions between you and the Seller will be governed by the terms and conditions of the Seller.
3. The Company does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Application. The Company does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Application. The Company accepts no liability for any errors or omissions, whether on behalf of itself or third parties.
4. The Company is not responsible for any non-performance or breach of any contract entered into between you and the Sellers. The Company cannot and does not guarantee that you and/or the Sellers will perform any transaction concluded on the Application. The Company shall not and is not required to mediate or resolve any dispute or disagreement between you and the Sellers.
5. You are advised to independently verify the bona fides of any particular Seller that you choose to deal with on the Application and use your best judgment in that behalf.
6. The Company does not at any point of time during any transaction between you and the Seller on the Application gain title to or have any rights or claims over the products or services offered by the Seller to you. The Company is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.
7. It is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and you.
8. You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the Seller(s) that you transact with. Pricing on any product(s) as is reflected on the Application may due to some technical issue, typographical error or product information published by the Seller be incorrectly reflected and in such an event the Seller reserves the right to refuse sale of the item(s).
9. The Company does not claim any ownership rights in the text, files, images including photos, videos, sounds, musical works or any UGC that you submit, submit or publish on the Application. After posting any UGC on the Application, you continue to own the rights that you may have in that UGC, subject to the limited license set out here.
    5. Cancellation</p>

<p>You may cancel your order anytime of placing the order by cancelling through the Application or intimating by chat as the booking channel requires. In such a case the Seller will refund any payments already made by you for the order, based on the seller’s refund policy. If we suspect any fraudulent transaction by you or any transaction which violates the terms and conditions of using the Application, we, at our sole discretion, reserve the right to initiate cancellation of such orders.</p>

    <p>6. Pricing and Product Availability</p>

<p>1. The Company will display on the Application, information on price and availability of the products and services sold, wherever specific Sellers are mapped and are available. Although prices of most of the products and services do not fluctuate on a daily basis, prices of some commodities may change on a daily basis. For any order, the price shall be the price prevailing at the date on which the order is placed. The prices listed on the Application are not negotiable.
2. Despite the best efforts of the Company, such information on the price and availability of products or services may be inaccurately displayed on the Application. The Company reserves the right to correct any and all errors when they do occur and the Company does not honor inaccurate or erroneous prices. The prices on the Application are also subject to change without notice.</p>

    <p>7. Payment</p> 

<p>The Company offers multiple payment options to you on the Application which are collected on behalf of the Seller, upon authorization:</p>

<p>1. Online Payment: You can make online payments using your credit card or debit card or through net banking (RTGS/NEFT/IMPS);
2. Offline Payment: You can complete the order online and then make payments to the Seller by cash on delivery to the delivery personnel.</p>

    <p>8. Delivery</p>

1. Any delivery or pick up timings of items are based on service shall be as per the Seller’s internal policy and the Company shall not, at any time, be responsible for dispatch, delivery or shipping of any products or services.
2. In the event that your order cannot be delivered on account of a mistake by you (i.e. wrong name or address or any other wrong information) any extra cost incurred by the Company for redelivery shall be claimed from you.
9. Usage of promo code by the Company

1. The Company has the right to refuse the usage of any promo code at any point of time. Promo codes which have expired cannot be used on the Application.
2. The Company can at any time ask you for the proof of having received the promo code.
3. Promo codes can be used only on specific orders as deemed fit by the Company.
4. Promo codes, at the Company's discretion, are applicable on certain items, on specific orders, or on specific dates and occasions.
5. Promo codes cannot be clubbed with any other special offer running on the Application.
6. For a payment received after the expiry of the promo code the discount will not be applicable on that order.
10. Copyright and Database Rights

1. All software used on the Application is the property of the Company or its software suppliers. You shall not systematically extract and/or re-utilize parts of the contents of the Application without the Company’s express written consent. In particular, you shall not utilize any data mining, robots, or similar data gathering and extraction tools to extract (either once or a number of times) for re-utilization of any substantial parts of the Application, without the Company’s prior and express written consent.
2. You shall not create and/or publish your own database that features substantial parts of the Application (e.g. prices and product listings) without the Company’s express written consent. Your personal and non-commercial use of the Application shall be subjected to the following restriction (i) you may not modify any content of the Application, including but not limited to, any public display, description, performance, sale, rental, pricing of the product; (ii) you may not decompile, reverse engineer, or disassemble the content, or (iii) remove any copyright, trademark registration, or other proprietary notices from the content. You further agree not to access or use the Application in any manner that may be harmful to the operation of the Application or its content.
11. Trademarks 

“Motley” and other marks indicated on the Application are trademarks of the Company in the Indian jurisdictions. All other trademarks not owned by the Company that appear on the Application are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by the Company.

12. Communications

1. Visiting the Application or sending emails to the Company constitutes electronic communication by you with the Company. The Company communicates with you by email or by posting notices on the Application. For contractual purposes, you consent to receive communications from the Company electronically and agree that all agreements, notices, disclosures and other communications that are provided to you electronically satisfy any legal requirement stipulating that those communications be in writing. This condition does not affect your statutory rights.
2. You understand that once you register on the Application, you will receive short message service (“SMS”) messages from the Company on your registered mobile number. These messages could relate to your registration, or any updates and promotions that are undertaken by the Company. Please note that the Company will send these SMS messages only to the registered mobile number or such other number that you may designate for any particular purpose.

13. Termination

1. In the event that you breach these Terms of Use or in the event that any other user or a third party reports violation of any of its rights as a result of your use of the Services, the Company reserves the right, to suspend or terminate such your access to the Application with or without notice to you, and to exercise any other remedy available under the law.
2. The Company shall have the right to indefinitely suspend or block access to your membership on the Application and/or refuse to provide you access to the Application:
1. If you engage in or are suspected of engaging in any illegal, fraudulent or abusive activity; or
2. If you provide any information that is untrue, inaccurate, not current or incomplete in any respect or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the Terms of Use.

3. Upon suspension or termination, your right to avail the Services on the Application shall immediately cease and the Company reserves the right to remove or delete information regarding you that is available with the Company, including but not limited to login, account information and information posted by you.
14. Amendments 

The Company reserves the right to make changes to our Application, policies, and these Terms of Use at any time. You will be subject to the Terms of Use in force at the time that you use the Application or at the time you place orders on the Application, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions are deemed invalid, void, or for any reason unenforceable, such condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.

15. Disclaimer, Indemnity and Limitation of Liability: You expressly understand and agree that:

1. The information, content and materials on the Application and / or Services are provided on an "as is" and "as available" basis. The Company and all its subsidiaries, affiliates, officers, employees, agents, partners and licensors disclaim all warranties of any kind, either express or implied, including but not limited to, implied warranties on merchantability, fitness for a particular purpose and non-infringement. The content of the Application has been provided in good faith. The content may contain inaccuracies or typographical errors.
2. The Company makes all reasonable efforts to display the products listed for sale on the Application as accurately as possible. However the Company cannot guarantee that the users’ monitor's display of any product color, texture or detail will be accurate. The Company does not warrant that product descriptions or other content are accurate, complete, reliable current or error free. While the Company makes every effort to ensure that the products are described and priced accurately, in the event that an item is deemed to be priced incorrectly, the Company reserves the right to refuse the sale of that item.
3. The Company does not warrant that the functions contained in content, information and materials on the Application and / or Services, including, without limitation any third party sites or services linked to the Application and / or Services will be uninterrupted, timely or error-free, that the defects will be rectified, or that the Application or the servers that make such content, information and materials available are free of viruses or other harmful components.
4. Any material downloaded or otherwise obtained through the Application and / or Services are accessed at your own risk, and you will be solely responsible for any damage or loss of data that results from such download to your computer system.
5. You acknowledge that when you access a link that leaves the Application, the site you will enter into is not controlled by the Company and different terms of use and privacy policy may apply. By accessing links to other sites, you acknowledge that the Company is not responsible for those sites. The Company reserves the right to disable links from third-party sites to the Application, although the Company is under no obligation to do so.
6. You hereby indemnify, defend, and hold the Company, the Company's distributors, agents, representatives and other authorized users, and each of the foregoing entities' respective resellers, distributors, service providers and suppliers, and all of the foregoing entities' respective officers, directors, owners, employees, agents, representatives, harmless from and against any and all losses, damages, liabilities and costs arising from your use of the Application.
7. You expressly understand that under no circumstances, including, but not limited to, negligence, shall the Company be liable to you or any other person or entity for any direct, indirect, incidental, special, or consequential damages, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses, resulting from circumstances, including but not limited to: (i) the use or the inability to use the Application and / or services; or (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the Application and / or services or (iii) unauthorized access to or alteration of the users’ transmissions or data; (iv) statements or conduct of any third party on the Application and / or services; or (v) any other matter relating to the Application and / or services.
8. The Company or any of the foregoing entities' respective resellers, distributors, service providers and suppliers be relieved of all its responsibilities, if any, in the event of failure of performance resulting directly or indirectly from an act of force majeure or causes beyond the Company's reasonable control including, without limitation, acts of god, war, equipment and technical failures, electrical power failures or fluctuations, strikes, labour disputes, riots, civil disturbances, shortages of labour or materials, natural disasters, orders of domestic or foreign courts or tribunals, non-performance of third parties, or any reasons beyond the reasonable control of the company or any of the foregoing entities' respective resellers, distributors, service providers and suppliers. You further acknowledge and agree that neither the Company nor any of the foregoing entities' respective resellers, distributors, service providers and suppliers are responsible or liable for (a) any incompatibility between the Application and / or services and any other site, service, software or hardware or (b) any delays or failures that users may experience with any transmissions or transactions relating to the Application in an accurate or timely manner.

16. Waiver 

No term of these Terms of Use shall be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by the Company. Any consent by the Company to, or waiver of a breach by you, whether expressed or implied, shall not constitute consent to, waiver of, or excuse for any other different or subsequent breach.

17. Governing Law and Jurisdiction

Any dispute, claim or controversy arising out of, or relating to the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of these Terms of Use, or to your use of the Application or the Service or information to which it gives access, shall be determined by arbitration in India, before a sole arbitrator. Arbitration shall be conducted in accordance with the Arbitration and Conciliation Act, 1996. The seat of such arbitration shall be Pune. All proceedings of such arbitration, including, without limitation, any awards, shall be in the English language. The award shall be final and binding on the parties.

18. Severability 

If any provision of these Terms of Use is held by a court of competent jurisdiction or arbitral tribunal to be unenforceable under applicable law, then such provision shall be excluded from these Terms of Use and the remainder of these Terms of Use shall be interpreted as if such provision were so excluded and shall be enforceable in accordance with its terms; provided however that, in such event these Terms of Use shall be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction or arbitral tribunal.

19. Complete Understanding

These Terms of Use contain the entire understanding between the parties, and there are no other written or oral understandings or promises between the parties with respect to the subject matter of these Terms of Use other than those contained or referenced in these Terms of Use.

20. Contact Us

If you have any questions about these Terms, please contact us on dakkhandigitalmarketing@gmail.com   